### ISSUE TITLE
Hardware revision request: Voltage divider jumper pad

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/MicroMod_Data_Logging_Carrier#1]
Hey folks,

If at some point there is a hardware revision of the MicroMod Data Logger Carrier Board, I would strongly suggest the addition of a jumper pad at the top of the 10kΩ/20kΩ voltage divider that would allow users to cut the voltage supply.

At present, this divider draws a constant 200 uA at 6V and there is no way to disable it, save for cutting the trace, or removing the SMD resistors with a hot air rework station. 

Cheers,
Adam

**Comment by nseidle** [comment]
A fine idea! Will do.

**Comment by adamgarbo** [comment]
Hey @nseidle,

I received a couple of MicroMod Data Logger Carrier Boards today. With the voltage divider enabled and a MicroMod Artemis Processor and 4.2 V lithium battery, I measure a deep sleep current of **~0.7 mA (700 uA)**.

Disabling the voltage divider, cutting the 3V3 and VIN jumper pads, disabling Qwiic and peripheral regulators through software, charging the RTC battery to full and removing the microSD card results in a quiescent draw of **0.56 mA (560 uA)**.

It's at least good to see the expected current draw of the voltage divider is removed when breaking the circuit. I can create a separate issue that identifies the other major current draw culprits and proposes some solutions to improve the power efficiency of the board.

Cheers,
Adam
