### ISSUE TITLE
incorrect information about power control

### ISSUE THREAD

**Issue by paulvha** [sparkfun/MicroMod_Data_Logging_Carrier#6]
Looking at the schematics, the hook-up guide, and the examples, the information about the power control is confusing/incorrect.

For both (G1 / Peripheral and G2 / QWIIC) the Enable pin on the LDO is pulled high with a resistor. Hence the power is ALWAYS ON !
_There is NO need for doing a power ON unless GPIO was pulled LOW in the sketch before!_ If people want to preserve power, they should power off the relevant LDO(s)

The hookup guide (https://learn.sparkfun.com/tutorials/micromod-data-logging-carrier-board-hookup-guide) states : 

**Take note both Qwiic and 3V3 peripheral power are controlled with a P-Channel MOSFET so the logic is reversed (Power ON = LOW and Power OFF = HIGH).**

### This is 3 times incorrect : 
1. There is NO MOSFET, but an LDO
2. Turning  POWER OFF = LOW  (NOT HIGH)
3. Turning POWER ON = HIGH ( which is already due to the pullup resistors.)

regards,
Paul

**Comment by nseidle** [comment]
Thanks! Fixed.
